### ISSUE TITLE
[FIX] training script for python3.5

### ISSUE THREAD

**Issue by ruohoruotsi** [Niger-Volta-LTI/yoruba-adr#6]
The paved-road for this project is python3.6 (soon 3.7), but we should support python3.5. @dadelani  has reported some errors with the training script.  Ensure that we retain backward compatibility with python3.5.

_I tried running the code on our server with python 3.5, it gave some encoding errors. I tried it on another system with python 3.6 and it works, since i don't have root permission, i need to find a way to make sure python3.5 works for the code_

`Traceback (most recent call last):
  File "/work/smg/v-david/try_project/yoruba-adr/src/make_parallel_text.py", line 172, in <module>
    main()
  File "/work/smg/v-david/try_project/yoruba-adr/src/make_parallel_text.py", line 159, in main
    examples = list(make_data(ARGS.source_file, ARGS.min_len, ARGS.max_len))
  File "/work/smg/v-david/try_project/yoruba-adr/src/make_parallel_text.py", line 111, in make_data
    print("Skipping: " + line2)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-25: ordinal not in range(128)`

**Comment by ruohoruotsi** [comment]
@dadelani I cannot reproduce the issue. I freshly installed `Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)`, then all the requirements, then ran the training script and everything worked fine. The training log is below
[python3.5_debug_log.txt](https://github.com/Niger-Volta-LTI/yoruba-adr/files/2888559/python3.5_debug_log.txt)

Perhaps the problem is that in `make_parallel_text.py` we are printing a unicode character, but your terminal doesn't support it. Maybe because it's localized for German? 

Can you please have a look at these solutions/diagnostics to ensure your locales are setup correctly: 
- https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20/31987791#31987791
- https://unix.stackexchange.com/questions/3218/ssh-and-character-encoding
- issue the command `locale` from your terminal. I get the following output. What is yours?
```
iroro$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
```

**Comment by ruohoruotsi** [comment]
David has confirmed this issue is an isolated one. Closing now.
